name: transactions

publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.17.6 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.2
  redux: ^5.0.0
  flutter_redux: ^0.10.0
  get_it: ^7.6.0
  flutter_redux_navigation: ^0.7.1
  logger: ^2.0.1

dev_dependencies:
  flutter_test:
    sdk: flutter

  flutter_lints: ^2.0.0
  redux_logging: ^0.5.1

flutter:

  uses-material-design: true